package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/spf13/cobra"
)

func installCmd() *cobra.Command {
	return &cobra.Command{
		Use:          "install [bash|zsh]",
		Short:        "Install shell integration shim",
		Args:         cobra.MaximumNArgs(1),
		SilenceUsage: true,
		Run: func(cmd *cobra.Command, args []string) {
			HandleInstall(args)
		},
	}
}

const shimBash = `#!/usr/bin/env bash
# tai shell integration shim — generated by: tai install
# Source this from a shell keybinding to use tai interactively.
tai_cmd=%s

cmd=$(TAI_SHIM=1 FORCE_COLOR=1 $tai_cmd ask "$@" </dev/tty)
exit_code=$?
if [[ $exit_code -eq 0 && -n "$cmd" ]]; then
  history -s -- "$cmd"
  READLINE_LINE=""
  READLINE_POINT=0
  eval -- "$cmd"
fi
`

const shimZsh = `#!/usr/bin/env zsh
# tai shell integration shim — generated by: tai install
# Source this from a shell keybinding to use tai interactively.
tai_cmd=%s

cmd=$(TAI_SHIM=1 FORCE_COLOR=1 command $tai_cmd ask "$@" </dev/tty)
exit_code=$?
if [[ $exit_code -eq 0 && -n "$cmd" ]]; then
  BUFFER="$cmd"
  CURSOR=$#BUFFER
  zle reset-prompt
fi
`

// HandleInstall creates an executable shim script at the best user bin directory.
// Usage: tai --install [bash|zsh]
func HandleInstall(args []string) {
	targetShell := resolveShell(args)

	binPath, err := os.Executable()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error determining binary path: %v\n", err)
		os.Exit(1)
	}
	if resolved, err := filepath.EvalSymlinks(binPath); err == nil {
		binPath = resolved
	}

	binDir := userBinDir()
	if err := os.MkdirAll(binDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating %s: %v\n", binDir, err)
		os.Exit(1)
	}

	scriptPath := filepath.Join(binDir, "tai")
	script := fmt.Sprintf(shimTemplate(targetShell), singleQuote(binPath))
	if err := os.WriteFile(scriptPath, []byte(script), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error writing shim to %s: %v\n", scriptPath, err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Installed %s shim to %s\n\n", targetShell, scriptPath)
}

func shimTemplate(targetShell string) string {
	if targetShell == "zsh" {
		return shimZsh
	}
	return shimBash
}

// singleQuote wraps s in single quotes, escaping any single quotes within.
func singleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

// userBinDir returns ~/.local/bin, falling back to ~/bin if it exists and is in $PATH.
func userBinDir() string {
	home, _ := os.UserHomeDir()

	localBin := filepath.Join(home, ".local", "bin")
	if _, err := os.Stat(localBin); err == nil {
		return localBin
	}

	homeBin := filepath.Join(home, "bin")
	if slices.Contains(filepath.SplitList(os.Getenv("PATH")), homeBin) {
		return homeBin
	}

	return localBin // will be created
}

// resolveShell returns the target shell from args or auto-detects from $SHELL.
func resolveShell(args []string) string {
	if len(args) > 0 {
		switch args[0] {
		case "bash", "zsh":
			return args[0]
		default:
			fmt.Fprintf(os.Stderr, "unknown shell %q — supported: bash, zsh\n", args[0])
			os.Exit(1)
		}
	}
	switch filepath.Base(os.Getenv("SHELL")) {
	case "bash", "zsh":
		return filepath.Base(os.Getenv("SHELL"))
	default:
		fmt.Fprintln(os.Stderr, "could not detect shell from $SHELL, defaulting to bash — use --install bash|zsh to override")
		return "bash"
	}
}
