package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

func widgetCmd() *cobra.Command {
	var key string

	cmd := &cobra.Command{
		Use:   "widget [bash|zsh]",
		Short: "Generate the widget script with keybinding for the specified shell",
		Long: `Generate the widget script that defines the _tai_widget function and binds it to a key.

Load it into your shell with:
  eval "$(tai widget bash)"    # or zsh

To persist across sessions, add the eval line to your shell config:
  echo 'eval "$(tai widget bash)"' >> ~/.bashrc`,
		Args:         cobra.MaximumNArgs(1),
		SilenceUsage: true,
		Run: func(cmd *cobra.Command, args []string) {
			handleWidget(args, key)
		},
	}

	cmd.Flags().StringVarP(&key, "key", "k", "", `key binding to use (default: \C-t for bash, ^T for zsh)`)
	return cmd
}

const widgetBash = `# tai widget — generated by: tai widget bash
# Load with: eval "$(tai widget bash)"

_tai_widget() {
  local tai_cmd=%s
  local cmd exit_code
  cmd=$(TAI_WIDGET=1 FORCE_COLOR=1 "$tai_cmd" ask </dev/tty)
  exit_code=$?
  if [[ $exit_code -eq 0 && -n "$cmd" ]]; then
    history -s -- "$cmd"
    eval -- "$cmd"
  fi
}

bind -x '"%s": _tai_widget'
`

const widgetZsh = `# tai widget — generated by: tai widget zsh
# Load with: eval "$(tai widget zsh)"

_tai_widget() {
  local tai_cmd=%s
  local cmd exit_code
  cmd=$(TAI_WIDGET=1 FORCE_COLOR=1 command "$tai_cmd" ask </dev/tty)
  exit_code=$?
  if [[ $exit_code -eq 0 && -n "$cmd" ]]; then
    BUFFER="$cmd"
    CURSOR=$#BUFFER
    zle accept-line
  fi
}

zle -N _tai_widget
bindkey '%s' _tai_widget
`

func handleWidget(args []string, key string) {
	targetShell := resolveShell(args)

	binPath, err := os.Executable()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error determining binary path: %v\n", err)
		os.Exit(1)
	}
	if resolved, err := filepath.EvalSymlinks(binPath); err == nil {
		binPath = resolved
	}

	if key == "" {
		if targetShell == "zsh" {
			key = "^T"
		} else {
			key = `\C-t`
		}
	}

	template := widgetBash
	if targetShell == "zsh" {
		template = widgetZsh
	}

	fmt.Printf(template, singleQuote(binPath), key)
}

// resolveShell returns the target shell from args or auto-detects from $SHELL.
func resolveShell(args []string) string {
	if len(args) > 0 {
		switch args[0] {
		case "bash", "zsh":
			return args[0]
		default:
			fmt.Fprintf(os.Stderr, "unknown shell %q — supported: bash, zsh\n", args[0])
			os.Exit(1)
		}
	}
	switch filepath.Base(os.Getenv("SHELL")) {
	case "bash", "zsh":
		return filepath.Base(os.Getenv("SHELL"))
	default:
		fmt.Fprintln(os.Stderr, "could not detect shell from $SHELL, defaulting to bash — pass bash|zsh to override")
		return "bash"
	}
}

// singleQuote wraps s in single quotes, escaping any single quotes within.
func singleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}
